frob3 makefile & files.  untested.

diff --git a/frob3/configure b/frob3/configure
--- a/frob3/configure
+++ b/frob3/configure
@@ -1,4 +1,6 @@
 #!/bin/bash
+set -eu
+exec >&2
 
 function fail () {
   echo "FAILURE: $*" >&2
@@ -8,43 +10,38 @@ function fail () {
 BUILD="$PWD"
 echo "BUILD directory : $BUILD"
 F=$(dirname $0)
-# FLONG=$(cd $(dirname $0) && pwd || fail Cannot determine directory of script: $0 )
 echo "FROB3 directory : $F"
 
-PREFIX=${PREFIX:-install}
-case $# in
-  1 )
-    case $1 in
-      --prefix=* )
-        PREFIX=$(expr match "X$1" 'X--prefix=\(.*\)')
-        echo "got PREFIX=$PREFIX"
-        ;;
-    esac
-    ;;
-esac
+LWASM=$(which lwasm || fail "Cannot find 'lwasm' command.")
+LWLINK=$(which lwlink || fail "Cannot find 'lwlink' command.")
+CMOC=$(which cmoc || fail "Cannot find 'cmoc' command.")
+GCC6809=$(which m6809-unknown-gcc || fail "Cannot find 'm6809-unknown-gcc' command.")
+OS9=$(which os9 || fail "Cannot find 'os9' command.")
+DECB=$(which decb || fail "Cannot find 'decb' command.")
+GO=$(which go || fail "Cannot find 'go' command.")
 
-echo "INSTALL prefix : $PREFIX"
+test -x "$LWASM" || fail "Cannot find 'lwasm' command."
+test -x "$LWLINK" || fail "Cannot find 'lwlink' command."
+test -x "$CMOC" || fail "Cannot find 'cmoc' command."
+test -x "$GCC6809" || fail "Cannot find 'm6809-unknown-gcc' command."
+test -x "$OS9" || fail "Cannot find 'os9' command."
+test -x "$DECB" || fail "Cannot find 'decb' command."
+test -x "$GO" || fail "Cannot find 'go' command."
 
-CMOC=$(which cmoc)
-GCC6809=$(which m6809-unknown-gcc)
-OS9=$(which os9)
-DECB=$(which decb)
-GO=$(which go)
-
-test -z "$CMOC" && fail "Cannot find 'cmoc' command."
-test -z "$GCC6809" && fail "Cannot find 'm6809-unknown-gcc' command."
-test -z "$OS9" && fail "Cannot find 'os9' command."
-test -z "$DECB" && fail "Cannot find 'decb' command."
-test -z "$GO" && fail "Cannot find 'go' command."
-
+echo Found lwasm at $LWASM
+echo Found lwlink at $LWLINK
 echo Found cmoc at $CMOC
 echo Found m6809-unknown-gcc at $GCC6809
 echo Found os9 at $OS9
 echo Found decb at $DECB
 echo Found go at $GO
 
-cat <<,,, >config.bash
+echo Writing config.txt
+cat <<,,,,,,,, >config.txt
 export F=$F
+
+export LWASM=$LWASM
+export LWLINK=$LWLINK
 
 export CMOC=$CMOC
 export CMOCI=$(dirname $(dirname $CMOC))/share/cmoc/include
@@ -55,94 +52,7 @@ export OS9=$OS9
 export DECB=$DECB
 export GO=$GO
 export BUILD=$BUILD
-export PREFIX=$PREFIX
-,,,
+,,,,,,,,
 
-############################
-cp -v $F/Makefile2 Makefile
-exit 0
-############################
-
-( # Start writing Makefile.
-cat <<,,,
-F       = $F
-CMOC    = $CMOC
-GCC6809 = $GCC6809
-OS9     = $OS9
-DECB    = $DECB
-GO      = $GO
-PREFIX  = $PREFIX
-####
-FROBLIB_C = $(echo $F/froblib/*.c)
-WIZ_C = $(echo $F/wiz/*.c)
-OS9_C = $(echo $F/os9/frobos9.c)
-NCL_C = $(echo $F/ncl/*.c)
-NCL_H = $(echo $F/ncl/*.h)
-LIB1 = \$(FROBLIB_C) \$(WIZ_C) \$(OS9_C)
-HDRS = $(echo $F/*.h)
-####
-
-,,,
-
-cat $F/Makefile.in 
-
-AXIOM_CFILES=
-AXIOM_MODS=
-for x in $F/axiom/[a-t]*.c
-do
-  b=$(basename $x .c)
-  AXIOM_CFILES="$AXIOM_CFILES $x"
-  AXIOM_MODS="$AXIOM_MODS $b.o"
-  sed -e 's/^[+]/\t/' <<,,,
-
-$b.s: $x  \$(LIB1) \$(HDRS)
-+gcc6809 -S -I$F/.. -Os -fomit-frame-pointer --std=gnu99 -Wall -Werror -D'NEED_STDLIB_IN_NETLIB3' $x
-
-$b.o: $b.s
-+lwasm  --obj --pragma=undefextern --pragma=cescapes --pragma=importundefexport --pragma=newsource -l'$b.list' -o $b.o $b.s
-
-,,,
-done
-
-sed -e 's/^[+]/\t/' <<,,,
-
-GCC6809LIB = -L'$(dirname $GCC6809)/../lib/gcc/m6809-unknown/4.6.4/' -lgcc
-
-axiom.temp: $AXIOM_MODS
-+lwlink -b -o axiom.temp  $AXIOM_MODS  \$(GCC6809LIB)
-
-axiom-whole: $AXIOM_CFILES
-+cat $AXIOM_CFILES > _axiom_whole.c
-+gcc6809 -S -I$F/.. -Os -fwhole-program -fomit-frame-pointer --std=gnu99 -Wall -Werror -D'NEED_STDLIB_IN_NETLIB3' _axiom_whole.c
-
-,,,
-
-NET_CMDS=
-for x in $F/net-cmds/f-*.c
-do
-  b=$(basename $x)
-  t=$(echo $b | sed -e 's/^f-/f./' -e 's/[.]c$//')
-  NET_CMDS="$NET_CMDS $t.os9cmd"
-  sed -e 's/^[+]/\t/' <<,,,
-$t.os9cmd: $x \$(LIB1) \$(HDRS)
-+bash \$F/Compile.bash $t $x \$(LIB1)
-
-,,,
-done ;# > __net_cmds.mk
-
-sed -e 's/^[+]/\t/' <<,,,
-f.ncl.os9cmd:  \$(NCL_C) \$(NCL_H) \$(LIB1)
-+bash \$F/Compile.bash f.ncl \$(NCL_C) \$(LIB1)
-
-NET_CMDS = $NET_CMDS
-_net_cmds: \$(NET_CMDS)
-
-NCL_CMDS = f.ncl.os9cmd
-_ncl_cmds: \$(NCL_CMDS)
-
-,,,
-
-# cat __net_cmds.mk
-
-# rm __net_cmds.mk
-) > Makefile
+cp -v $F/Makefile.in Makefile
+echo "OKAY."
